BOARD_WIDTH = 600
BOARD_HEIGHT = 600
BOUNDARY_THICKNESS = 10
MAX_Y = (BOARD_HEIGHT / 2) - BOUNDARY_THICKNESS
MIN_Y = -((BOARD_HEIGHT / 2) - BOUNDARY_THICKNESS)
MAX_X = (BOARD_WIDTH / 2) - BOUNDARY_THICKNESS
MIN_X = -((BOARD_WIDTH / 2) - BOUNDARY_THICKNESS)
