# Window Size and boundaries
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
BUFFER = 20
TOP_BOUNDARY = (WINDOW_HEIGHT / 2) - BUFFER
BOTTOM_BOUNDARY = -((WINDOW_HEIGHT / 2) - BUFFER)
RIGHT_BOUNDARY = WINDOW_WIDTH / 2
LEFT_BOUNDARY = -(WINDOW_WIDTH / 2)

# Paddle related constants
PADDLE_BORDER_PAD = 50
START_X_LEFT = -((WINDOW_WIDTH / 2) - PADDLE_BORDER_PAD)
START_X_RIGHT = (WINDOW_WIDTH / 2) - PADDLE_BORDER_PAD
PADDLE_MOVE_DISTANCE = 20
HEADING_DIRECTION = 90

# Ball related constants
WINDOW_MIDDLE = (0, 0)
BALL_MOVE_DISTANCE_X = (WINDOW_WIDTH / 2) * 0.025
BALL_MOVE_DISTANCE_Y = BALL_MOVE_DISTANCE_X - ((WINDOW_HEIGHT / 2) * 0.015)
BALL_COLLISION_WITH_PADDLE_RIGHT = START_X_RIGHT - 30
BALL_COLLISION_WITH_PADDLE_LEFT = START_X_LEFT + 30

# Directional Movement
RIGHT = "Right"
LEFT = "Left"
DOWN = "Down"
UP = "Up"

# Scoreboard related constants
SCOREBOARD_TOP_PAD = 125
SCOREBOARD_LEFT_POS_X = -((WINDOW_WIDTH / 2) - ((WINDOW_WIDTH / 2) / 1.5))
SCOREBOARD_RIGHT_POS_X = (WINDOW_WIDTH / 2) - ((WINDOW_WIDTH / 2) / 1.5)
SCOREBOARD_POS_Y = (WINDOW_HEIGHT / 2) - SCOREBOARD_TOP_PAD
